### ISSUE TITLE
“Thrice a day” - When exactly is this updated?

### ISSUE THREAD

**Issue by joe-scotto** [backtrackbaba/covid-api#12]
Title pretty much says it all... it seems that you manually trigger updates to the API but what times are these?

**Comment by backtrackbaba** [comment]
Hi @joe-scotto,

As mentioned in the README, our APIs are built upon data provided by [pomber](https://github.com/pomber/covid19) who internally consumes [JHU's](https://github.com/CSSEGISandData/COVID-19) data. Now, if you see the update frequency of JHU, you'll see that it has reduced to once a day which happens approximately at 00:00 GMT every day. Based on the updation of JHU, I had written automation to update the database a few minutes after they do their update.

The endpoint for the same still exists in the code, but the automation has removed due to the following reasons:

Our project essentially standardizes the data of JHU by using globally accepted ISO standards for the dates as well as the names. The data provided by JHU doesn't have standard country names. If you see [this file](https://github.com/backtrackbaba/covid-api/blob/master/data/country_name_to_iso.json) that I use to standardize includes all the names that JHU has and it's equivalent ISO code.

This can't be automated as there isn't a proper system of naming hence there has to be a human in the process to checks for mapping issues and simply adds it to the JSON.
Ex: Just yesterday they added a ship called MS Zaandam, which is stuck somewhere near the Netherlands. Now, if this would've been automated it would've broken the system as there isn't any country by that name. Hence, I had to [manually add an entry](https://github.com/backtrackbaba/covid-api/commit/4e85ea526df3f3c571d1953aa8084b02986b80a7) for it as `MSZ`

This is a reason why I update it locally first, to see what are the breaking changes and then trigger the update on prod manually.

Do let me know if you have any better process in mind or if you need any other help with the project

**Comment by backtrackbaba** [comment]
Closing the issue. Let me know if you face any other issue. I've striked-through the thrice a day part for now.
