### ISSUE TITLE
Has data already updated today?

### ISSUE THREAD

**Issue by hubciorz** [backtrackbaba/covid-api#9]
Good morning! (in some timezones)

I found somewhere that data should get updated "At minute 15 past hour 5, 13, and 2" - but what timezone? If GMT, data did not update today. Example: https://covidapi.info/api/v1/global/timeseries/2020-03-26/2020-03-27

https://github.com/pomber/covid19/blob/master/docs/timeseries.json has already been updated

**Comment by backtrackbaba** [comment]
There's a slight change in JHU's data in which pomber is built on. I'm testing the same locally and fixing it. Won't take more than 10 mins for it to be up.

I'll ping here once it's done

**Comment by hubciorz** [comment]
@backtrackbaba Thanks, you're awesome!

**Comment by backtrackbaba** [comment]
I had the automation up and running, but since JHU's data format isn't consistent I'm not using it as it was breaking stuff. At the mentioned cron intervals, I run that update script manually to check out the issues and fix them and then run them on the server.

The script is being run, you'll see the updated result right about now!

**Comment by hubciorz** [comment]
@backtrackbaba It's working now. Thank you!
